### ISSUE TITLE
crash on linux launch with indexOutOfBounds error

### ISSUE THREAD

**Issue by mattthw** [Wingman/wingman#9]
https://gist.github.com/mmccoy37/15ee6ece635589dcfa696b42463d7f97

**Comment by alexanderhenne** [comment]
This exception is thrown from within the game if the game does not cover a screen area of some minimum size defined in the game's code.

I know that it can be caused by pressing the "expand sidebar" button pictured below while the client is loading, but that doesn't seem to be your case.

**Does the client get automatically minimized/resized to an extremely small size after the launching stage is done?**

![untitled-1](https://cloud.githubusercontent.com/assets/8920674/21996250/90a68974-dc29-11e6-81b2-414669c7f574.png)

**Comment by mattthw** [comment]
issue was caused by not having wingman-core
